### ISSUE TITLE
HELP — Spanish Speaker Needed!

### ISSUE THREAD

**Issue by tajmone** [alan-if/alan-i18n#30]
We need the help of a native (or fluent) Spanish/Castilian speak for the update work of the _[Spanish Foundation Library]_.

Ideally, we're looking for someone who's willing to take on maintenance of the Spanish Library — i.e. working both on its code and text — but having someone who can help us out with the text work would be already a great start — i.e. proofreading changes to the library messages, helping with translation work from English, etc.

Our goal is to update the Spanish Library to meet the new changes in design and feature which we're applying to the _[English Foundation Library]_, so that both libraries will mirror each other when they reach v1.0.0, and are kept _en par_ henceforth.

Currently, updates to the Spanish library are being handled by [Tristano Ajmone] — i.e. me — who is Italian and can more or less understand Spanish (having lived in Spain for a while), but he can't write Spanish, which is his main obstacle when it comes to changes that will affect text output.

So, if you're an IF enthusiast who's willing to help us with the Spanish library, please reply to this post. If you have no experience with ALAN, don't worry, we'll be working together as a team, so we can work together on the code aspects. Also, programming ALAN is very easy to learn and it won't take long either.

[Spanish Foundation Library]: https://github.com/alan-if/alan-i18n/tree/main/alan_es "View the Spanish Foundation Library in the repository"
[English Foundation Library]: https://github.com/alan-if/alan-i18n/tree/main/alan_en "View the English Foundation Library in the repository"
[Tristano Ajmone]: https://github.com/tajmone "View Tristano Ajmone's GitHub profile"

**Comment by Rich15** [comment]
Hi! I'm a native Spanish speaker and think I could help. I have no experience with Alan (_in fact, I just know some JS and a little bit of Python_), but I could help you with translations and orthography corrections. 

Let me know what is exactly needed and I'll see if I can help :)

**Comment by tajmone** [comment]
Hi @Rich15, and thanks a lot for replying to our plea!

> Hi! I'm a native Spanish speaker and think I could help. I have no experience with Alan (in fact, I just know some JS and a little bit of Python), but I could help you with translations and orthography corrections.

That's really great. ALAN is indeed a simple programming language to learn, more on the prose side than the standard programming language, so if you've made it through JS you should have no problems learning ALAN at all.

In any case, we'd be working together on the library code, so we'll be at your disposal for any question you need. Your help with the translation, proofreading and understanding some of the original choice of terms will be indeed most precious.

Right now, I was about to leave the PC for a few hours, so I'll be answering in more detail (and with some practical examples) later one. In the meantime, thanks and welcome on board!

Tristano

**Comment by Rich15** [comment]
Thanks! Really looking to learn more and help.

> Hi @Rich15, and thanks a lot for replying to our plea!
> 
> That's really great. ALAN is indeed a simple programming language to learn, more on the prose side than the standard programming language, so if you've made it through JS you should have no problems learning ALAN at all.
> 
> In any case, we'd be working together on the library code, so we'll be at your disposal for any question you need. Your help with the translation, proofreading and understanding some of the original choice of terms will be indeed most precious.
> 
> Right now, I was about to leave the PC for a few hours, so I'll be answering in more detail (and with some practical examples) later one. In the meantime, thanks and welcome on board!
> 
> Tristano
>

**Comment by tajmone** [comment]
See #33!
