### ISSUE TITLE
Lib EN: 'brief' and 'verbose' not Meta Verbs 

### ISSUE THREAD

**Issue by tajmone** [alan-if/alan-i18n#5]
- [x] Make `brief` and `verbose` META verbs:
     - [x] English Library.
     - [x] Spanish Library.
------

I've noticed that in the English Library the commands _brief_ and _verbose_ (defined in [`brief.i`][brief.i] module) are not defined as meta verbs:

```alan
Syntax
  verbose = verbose.

Verb verbose
  Does
    Visits 0.
    "Verbose mode is now on."
End verb.


Syntax
  brief = brief.

Verb brief
  Does
    Visits 1000.
    "Brief mode is now on. Location descriptions will only be shown
     the first time you visit."
End verb.
```

It would probably make sense to make these two commands meta verbs, since they are out-of-world actions dealing with the game play, not the story.

[brief.i]: https://github.com/alan-if/alan-i18n/blob/main/alan_en/lib_en/brief.i

**Comment by tajmone** [comment]
# More Non-Meta Verbs

I've also noticed that none of the the verbs in the [`meta.i`][meta.i] module are defined as meta verbs either, even those dealing with out-of-world gameplay commands: _quit_, _save_, _restore_, _restart_, _score_.

Also, the _again_ command should probably be defined as a meta verbs, since it doesn't do anything except pointing out that it doesn't work, so it shouldn't consume a game turn IMO.

Basically, all the verbs defined in the [`meta.i`][meta.i] module should actually be meta verbs (which is why it was called "meta" in the first place), with the exception of _wait_, which is usually supposed to consume a player turn.

@thoni56, do you have an idea why these are not meta verbs? Was the `META` construct not available back then? 



[meta.i]: https://github.com/alan-if/alan-i18n/blob/main/alan_en/lib_en/meta.i

**Comment by thoni56** [comment]
`meta` was not available in Alan v2 nor in early versions of v3. But as mentioned elsewhere this library should be "modern, ideomatic Alan" so all such verbs should adopt the meta keyword as you suggest.
