### ISSUE TITLE
Spanish Foundation v0.4.0

### ISSUE THREAD

**Issue by tajmone** [alan-if/alan-i18n#56]
Pending tasks for upcoming Spanish Foundation `v0.4.0`:

- [ ] **Library code**:
    + [ ] Find new replacement name for `scenario` class.
- [x] **Vampiro**:
    + [x] Replace all `examinar` VERBs on `Escenario` with an `xDesc` attribute, when possible (i.e. when no other code is involved).
- [x] Fix Library version in:
    + [x] `Library.i`
    + [x] `alan_es/README.md` badge.
- [x] When release is ready:
    + [x] Fix release date (now `2021/12/xx`) in:
        * [x] `CHANGELOG.md`
        * [x] `Library.i`
    + [x] Update ES `CHANGELOG.md`
    + [x] Fix `PORT_STATUS.md` doc, adding `v0.4.0` as version fulling the "Honour `xDesc` in scenery" row.

**Comment by tajmone** [comment]
# On `scenery` Name

@Rich15, I agree with you that `scenery` is not a good choice. In Italian it means _sighting_, as in a _nice view_. But I also believe the choice is not quite accurate in English either, for it should be a word indicating a theatrical _prop_ (what I believe in Spanish would be _utilería escénica_).

I can't think of an Italian word for _prop_, besides "oggetto scenico" which is too long (like in Spanish). I looked up the Spanish translator but couldn't pinpoint a word that seems to fit either.

Maybe _accesorio_? At least it renders the idea of its purpose, as being just an accessory prop. Other words that come to mind: _ornamento_, _ornamentación_, _adorno_. Any good?

Ideally, in IF there are two types of scenic objects:

- _props_ — i.e. objects with the sole purpose of filling the stage, and implementing an examinable entity for things mentioned in the description (usually to provide atmosphere and mood), but which should offer no interaction besides examining (which is what this commit fixes with `xDesc` honouring).
- _backdrops_ — i.e. scenic backdrops which can be viewed in the background from one or more locations. Usually for implementing the Sky and its _props_ (clouds, sun, stars, etc.). In ALAN backdrops are achieved by placing them in a location which wraps multiple locations, forming a _region_ (in Inform7 terminology), so the player will see the backdrop in all locations inside that region.

The library only provides the first of these two, which is calling `scenery`.

> **IMPORTANT** — Note that in one of the next English library updates I'll be dropping the `scenery` class in favour of a `scenery` attribute, as discussed in #34. But this doesn't affect this Spanish release nor the choice of the alternative name. When the English library will have implemented the `scenery` attribute (lot's of changes involved, touching _every VERB_), we'll think about it.

**Comment by Rich15** [comment]
> @Rich15, I agree with you that scenery is not a good choice. In Italian it means sighting, as in a nice view.

In Spanish "escenario" means "stage", so it's really a bad choice too.

> Maybe _accesorio_? At least it renders the idea of its purpose, as being just an accessory prop. Other words that come to mind: _ornamento_, _ornamentación_, _adorno_. Any good?

I think _accesorio_ conveys a better idea of the purpose of `scenery`.

**Comment by tajmone** [comment]
> I think _accesorio_ conveys a better idea of the purpose of `scenery`.

The choice is up to you. But we can postpone it to when we'll have to change the `scenery` class to an attribute.

We probably should have this release just deal with the integration of the honoring `xDesc`, and move on.

If everything looks fine to you I'll fix the release date in all the various files, so then you can squash it into a single commit merge.

> PS — sorry for not having documented yet how each release bump requires some search & replace to fix the new Lib version and date in various places! Basically in the Spanish README the version number appear in the badge, defined toward the end in the reference links, lib date and version need to be fixed in the library source and in vampiro (which also need to be bumped up if it requires tweaking). I'll write a short memo somewhere in the repository.

**Comment by Rich15** [comment]
> The choice is up to you. But we can postpone it to when we'll have to change the `scenery` class to an attribute.
>
> We probably should have this release just deal with the integration of the honoring  `xDesc`, and move on.

I agree.  We'll change the name along with the future attribute.

Everything looks good to go then.

**Comment by tajmone** [comment]
# All Fixed!

Fixed dates, etc. and squash into a single commit.

Feel free to merge.
